# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(571, 428)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 541, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.odwrotnie = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.odwrotnie.setObjectName("odwrotnie")
        self.gridLayout.addWidget(self.odwrotnie, 3, 1, 1, 1)
        self.male = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.male.setObjectName("male")
        self.gridLayout.addWidget(self.male, 1, 1, 1, 1)
        self.value1 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.value1.setObjectName("value1")
        self.gridLayout.addWidget(self.value1, 0, 0, 1, 1)
        self.value2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.value2.setObjectName("value2")
        self.gridLayout.addWidget(self.value2, 5, 0, 1, 1)
        self.zmien = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.zmien.setObjectName("zmien")
        self.gridLayout.addWidget(self.zmien, 4, 1, 1, 1)
        self.duze = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.duze.setObjectName("duze")
        self.gridLayout.addWidget(self.duze, 2, 1, 1, 1)
        self.value1.raise_()
        self.odwrotnie.raise_()
        self.zmien.raise_()
        self.value2.raise_()
        self.duze.raise_()
        self.male.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.odwrotnie.setText(_translate("Dialog", "odwrotnie"))
        self.male.setText(_translate("Dialog", "małe"))
        self.zmien.setText(_translate("Dialog", "Zmień"))
        self.duze.setText(_translate("Dialog", "duże"))
